#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. script/homebrew

# Install gems:
gem install pry bundler --no-ri --no-rdoc

# dotvim install
ln -sfn ~/dotfiles/dotvim ~/.vim
ln -sfn ~/dotfiles/dotvim/vimrc ~/.vimrc
cd ~.vim; make install; cd -

# Run the install (I'd like to pull this out of rake, eventually)
rake install