#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. script/homebrew

# Install gems:
gem install pry bundler --no-ri --no-rdoc

# Run the install (I'd like to pull this out of rake, eventually)
rake install